package ptm;
import javax.swing.*;
import java.util.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
public class WeldingFields extends javax.swing.JFrame {
Connection con;
    PreparedStatement pst;
    ResultSet rs;
    DefaultTableModel d;
    Cart cart=new Cart();
 public void tbl() {
        try {
            pst = con.prepareStatement("select * from `welding`");
            rs = pst.executeQuery();
            ResultSetMetaData rsd = rs.getMetaData();
            d = (DefaultTableModel) tblw.getModel();
            d.setRowCount(0);
            while (rs.next()) {
                Vector v = new Vector();
                 v.add(rs.getString("Id"));
                v.add(rs.getString("Name"));
                v.add(rs.getString("Brand"));
                v.add(rs.getString("Model No"));
                v.add(rs.getString("Whole Sale"));
                v.add(rs.getString("R Sale"));
                v.add(rs.getString("Cost Price"));
                v.add(rs.getString("Total Quantity"));
                v.add(rs.getString("Show Room"));
                v.add(rs.getString("Godam"));
                v.add(rs.getString("Total Cost"));
                d.addRow(v);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Welding.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
 public void Connect() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            try {
                con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/ptm", "root", "");
            } catch (SQLException ex) {
                Logger.getLogger(Welding.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Welding.class.getName()).log(Level.SEVERE, null, ex);
        }}
    public WeldingFields() {
        initComponents();
        Connect();
        tbl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        btnbill = new javax.swing.JLabel();
        btnadd = new javax.swing.JLabel();
        btnupdate = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblht = new javax.swing.JLabel();
        lblaccess = new javax.swing.JLabel();
        btnwarning = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btncustomer = new javax.swing.JLabel();
        lblwire = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        lblpt = new javax.swing.JLabel();
        btncart = new javax.swing.JLabel();
        lblsp = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblw = new javax.swing.JTable();
        in = new javax.swing.JLabel();
        brand = new javax.swing.JLabel();
        mn = new javax.swing.JLabel();
        ws = new javax.swing.JLabel();
        res = new javax.swing.JLabel();
        cp = new javax.swing.JLabel();
        sr = new javax.swing.JLabel();
        godam = new javax.swing.JLabel();
        txtin = new javax.swing.JTextField();
        txtmn = new javax.swing.JTextField();
        txtws = new javax.swing.JTextField();
        txtrs = new javax.swing.JTextField();
        txtcp = new javax.swing.JTextField();
        txtsr = new javax.swing.JTextField();
        txtgodam = new javax.swing.JTextField();
        combobrand = new javax.swing.JComboBox<>();
        Id = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnwelding = new javax.swing.JLabel();
        btnchisel = new javax.swing.JLabel();
        btnbits = new javax.swing.JLabel();
        btnsafegaurd = new javax.swing.JLabel();
        btnhandle = new javax.swing.JLabel();
        btnchucknut = new javax.swing.JLabel();
        btnkeys = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnbill.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnbill.setForeground(new java.awt.Color(255, 255, 255));
        btnbill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-bill-24.png"))); // NOI18N
        btnbill.setText("Bill");
        btnbill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbillMouseClicked(evt);
            }
        });
        jPanel3.add(btnbill, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 130, 40));

        btnadd.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnadd.setForeground(new java.awt.Color(255, 255, 255));
        btnadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-add-24.png"))); // NOI18N
        btnadd.setText("Add");
        btnadd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnaddMouseClicked(evt);
            }
        });
        jPanel3.add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 130, 40));

        btnupdate.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnupdate.setForeground(new java.awt.Color(255, 255, 255));
        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-available-updates-26.png"))); // NOI18N
        btnupdate.setText("Update");
        btnupdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnupdateMouseClicked(evt);
            }
        });
        jPanel3.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 130, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 70, 130, 630));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search_26px.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, 30, -1));

        lblht.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblht.setForeground(new java.awt.Color(255, 255, 255));
        lblht.setText("Hand Tools");
        lblht.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblhtMouseClicked(evt);
            }
        });
        jPanel1.add(lblht, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 80, -1));

        lblaccess.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblaccess.setForeground(new java.awt.Color(255, 255, 255));
        lblaccess.setText("Accessories");
        lblaccess.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblaccessMouseClicked(evt);
            }
        });
        jPanel1.add(lblaccess, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 80, -1));

        btnwarning.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-warning-24.png"))); // NOI18N
        btnwarning.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnwarningMouseClicked(evt);
            }
        });
        jPanel1.add(btnwarning, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 30, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-drill-64.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 70, 60));

        btncustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-user-24.png"))); // NOI18N
        btncustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncustomerMouseClicked(evt);
            }
        });
        jPanel1.add(btncustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 30, -1, -1));

        lblwire.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblwire.setForeground(new java.awt.Color(255, 255, 255));
        lblwire.setText("Wire");
        lblwire.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblwireMouseClicked(evt);
            }
        });
        jPanel1.add(lblwire, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 90, -1));

        txtsearch.setBackground(new java.awt.Color(0, 51, 102));
        txtsearch.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtsearch.setForeground(new java.awt.Color(255, 255, 255));
        txtsearch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        txtsearch.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });
        jPanel1.add(txtsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 30, 210, -1));

        lblpt.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblpt.setForeground(new java.awt.Color(255, 255, 255));
        lblpt.setText("Power Tools");
        lblpt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblptMouseClicked(evt);
            }
        });
        jPanel1.add(lblpt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 90, 20));

        btncart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-shopping-cart-24.png"))); // NOI18N
        btncart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncartMouseClicked(evt);
            }
        });
        jPanel1.add(btncart, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 30, 40, 30));

        lblsp.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblsp.setForeground(new java.awt.Color(255, 255, 255));
        lblsp.setText("Spare Parts");
        lblsp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblspMouseClicked(evt);
            }
        });
        jPanel1.add(lblsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 90, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 70));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblw.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tblw.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Item Name", "Brand", "Model No", "Whole Sale", "R Sale", "Cost Price", "Total Quantity", "Show Room", "Godam", "Total Cost"
            }
        ));
        tblw.setShowHorizontalLines(true);
        tblw.setShowVerticalLines(true);
        tblw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblwMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblw);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 930, -1));

        in.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        in.setText("Item Name");
        jPanel2.add(in, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 90, -1));

        brand.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        brand.setText("Brand");
        jPanel2.add(brand, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 70, -1));

        mn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        mn.setText("Model No.");
        jPanel2.add(mn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 80, -1));

        ws.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ws.setText("Whole Sale");
        jPanel2.add(ws, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 90, -1));

        res.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        res.setText("Retail Sale");
        jPanel2.add(res, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 70, -1));

        cp.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cp.setText("Cost Price");
        jPanel2.add(cp, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, 80, -1));

        sr.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        sr.setText("Show Room");
        jPanel2.add(sr, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 90, -1));

        godam.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        godam.setText("Godam");
        jPanel2.add(godam, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 60, -1));

        txtin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtinActionPerformed(evt);
            }
        });
        jPanel2.add(txtin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 180, -1));
        jPanel2.add(txtmn, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 30, 180, -1));
        jPanel2.add(txtws, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 180, -1));
        jPanel2.add(txtrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 180, -1));
        jPanel2.add(txtcp, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 70, 180, -1));
        jPanel2.add(txtsr, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 180, -1));
        jPanel2.add(txtgodam, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 180, -1));

        combobrand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose a Brand", " " }));
        jPanel2.add(combobrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 180, 20));

        Id.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Id.setText("Id");
        jPanel2.add(Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 40, 20));
        jPanel2.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 108, 180, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 950, 630));

        jPanel4.setBackground(new java.awt.Color(0, 51, 102));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnwelding.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnwelding.setForeground(new java.awt.Color(255, 255, 255));
        btnwelding.setText("Welding Accessories");
        btnwelding.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnweldingMouseClicked(evt);
            }
        });
        jPanel4.add(btnwelding, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 150, 30));

        btnchisel.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnchisel.setForeground(new java.awt.Color(255, 255, 255));
        btnchisel.setText("Chisel");
        btnchisel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnchiselMouseClicked(evt);
            }
        });
        jPanel4.add(btnchisel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 100, 30));

        btnbits.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnbits.setForeground(new java.awt.Color(255, 255, 255));
        btnbits.setText("Bits");
        btnbits.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbitsMouseClicked(evt);
            }
        });
        jPanel4.add(btnbits, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 100, 30));

        btnsafegaurd.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnsafegaurd.setForeground(new java.awt.Color(255, 255, 255));
        btnsafegaurd.setText("Safe Gaurd");
        btnsafegaurd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsafegaurdMouseClicked(evt);
            }
        });
        jPanel4.add(btnsafegaurd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 100, 30));

        btnhandle.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnhandle.setForeground(new java.awt.Color(255, 255, 255));
        btnhandle.setText("Handle");
        btnhandle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhandleMouseClicked(evt);
            }
        });
        jPanel4.add(btnhandle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 100, 30));

        btnchucknut.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnchucknut.setForeground(new java.awt.Color(255, 255, 255));
        btnchucknut.setText("Chuck Nut");
        btnchucknut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnchucknutMouseClicked(evt);
            }
        });
        jPanel4.add(btnchucknut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 100, 30));

        btnkeys.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnkeys.setForeground(new java.awt.Color(255, 255, 255));
        btnkeys.setText("Keys");
        btnkeys.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnkeysMouseClicked(evt);
            }
        });
        jPanel4.add(btnkeys, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 100, 30));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 160, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtinActionPerformed

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
         String txt=txtsearch.getText();
          try {
              if(txt.matches("^[0-9]+$")){
            String query="SELECT * FROM `welding` Where `Model No`="+txt;
                pst=con.prepareStatement(query);
              rs=pst.executeQuery();
              tblw.setModel(DbUtils.resultSetToTableModel(rs));
              }
            else if (txt.matches("^[a-zA-Z0-9]+$")) {
    // Search by ID
    String query = "SELECT * FROM `welding` WHERE `Id` = '" + txt + "'";
    pst = con.prepareStatement(query);
              rs=pst.executeQuery();
              tblw.setModel(DbUtils.resultSetToTableModel(rs));
              }
               if(txt.matches("^[a-zA-Z]+$"))
              {
              String query="SELECT * FROM `welding` Where `Name` LIKE '%"+txt+"%'";
                pst=con.prepareStatement(query);
              rs=pst.executeQuery();
              tblw.setModel(DbUtils.resultSetToTableModel(rs));
              }
               if (txt.isEmpty()) {
    String query = "SELECT * FROM `welding`";
    pst = con.prepareStatement(query);
    rs = pst.executeQuery();
    tblw.setModel(DbUtils.resultSetToTableModel(rs));}
            } catch (SQLException ex) {
                Logger.getLogger(Welding.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_txtsearchKeyReleased

    private void btnaddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaddMouseClicked
     try {
              String Id = txtid.getText();
            String ItemName = txtin.getText();
            String Brand = (String) combobrand.getSelectedItem();
            String ModelNo = txtmn.getText();
            String WholeSale = txtws.getText();
            String RSale = txtrs.getText();
            String CostPrice = txtcp.getText();
            String ShowRoom = txtsr.getText();
            String Godam = txtgodam.getText();
            int TotalQuantity = Integer.parseInt(txtsr.getText()) + Integer.parseInt(txtgodam.getText());
            Double TotalCost = Double.parseDouble(txtcp.getText()) * TotalQuantity;
            pst = con.prepareStatement("INSERT INTO `welding`(`Id`,`Name`, `Brand`, `Model No`, `Whole Sale`, `R Sale`, `Cost Price`, `Total Quantity`, `Show Room`, `Godam`, `Total Cost`) VALUES (?,?,?,?,?,?,?,?,?,?,?)");
pst.setString(1, Id);
            pst.setString(2, ItemName);
            pst.setString(3, Brand);
            pst.setString(4, ModelNo);
            pst.setString(5, WholeSale);
            pst.setString(6, RSale);
            pst.setString(7, CostPrice);
            pst.setInt(8, TotalQuantity);
            pst.setString(9, ShowRoom);
            pst.setString(10, Godam);
            pst.setDouble(11, TotalCost);
            JOptionPane.showMessageDialog(this, "Added successfully!");
            pst.executeUpdate();
             txtid.setText("");
            txtin.setText("");
            combobrand.setSelectedItem("Choose a Brand");
            txtmn.setText("");
            txtws.setText("");
            txtrs.setText("");
            txtcp.setText("");
            txtsr.setText("");
            txtgodam.setText("");
            tbl();
        } catch (SQLException ex) {
            Logger.getLogger(WeldingFields.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnaddMouseClicked

    private void btnupdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnupdateMouseClicked
         try {
 String Id = txtid.getText();
            String ItemName = txtin.getText();
            String Brand = (String) combobrand.getSelectedItem();
            String ModelNo = txtmn.getText();
            String WholeSale = txtws.getText();
            String RSale = txtrs.getText();
            String CostPrice = txtcp.getText();
            String ShowRoom = txtsr.getText();
            String Godam = txtgodam.getText();
            int TotalQuantity = Integer.parseInt(txtsr.getText()) + Integer.parseInt(txtgodam.getText());
            Double TotalCost = Double.parseDouble(txtcp.getText()) * TotalQuantity;
            pst = con.prepareStatement("UPDATE `welding` SET `Id`=?,`Name`=?,`Brand`=?,`Whole Sale`=?,`R Sale`=?,`Cost Price`=?,`Total Quantity`=?,`Show Room`=?,`Godam`=?,`Total Cost`=? WHERE `Model No`=?");
            pst.setString(1, Id);
            pst.setString(2, ItemName);
            pst.setString(3, Brand);
            pst.setString(11, ModelNo);
            pst.setString(4, WholeSale);
            pst.setString(5, RSale);
            pst.setString(6, CostPrice);
            pst.setInt(7, TotalQuantity);
            pst.setString(8, ShowRoom);
            pst.setString(9, Godam);
            pst.setDouble(10, TotalCost);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Updated successfully!");
            btnupdate.setEnabled(true);
            txtid.setText("");
            txtin.setText("");
            combobrand.setSelectedItem("Choose a Brand");
            txtmn.setText("");
            txtws.setText("");
            txtrs.setText("");
            txtcp.setText("");
            txtsr.setText("");
            txtgodam.setText("");
            tbl();
            JFrame frame = new JFrame();
            frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        } catch (SQLException ex) {
            Logger.getLogger(WeldingFields.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnupdateMouseClicked

    private void tblwMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblwMouseClicked
         d = (DefaultTableModel) tblw.getModel();
        int sIndex = tblw.getSelectedRow();
        String id = d.getValueAt(sIndex, 0).toString();
        txtid.setText(d.getValueAt(sIndex, 0).toString());
        txtin.setText(d.getValueAt(sIndex, 1).toString());
        combobrand.setSelectedItem(d.getValueAt(sIndex, 2).toString());
        txtmn.setText(d.getValueAt(sIndex, 3).toString());
        txtws.setText(d.getValueAt(sIndex, 4).toString());
        txtrs.setText(d.getValueAt(sIndex, 5).toString());
        txtcp.setText(d.getValueAt(sIndex, 6).toString());
        txtsr.setText(d.getValueAt(sIndex, 8).toString());
        txtgodam.setText(d.getValueAt(sIndex, 9).toString());
        btnadd.setEnabled(true);
    }//GEN-LAST:event_tblwMouseClicked

    private void btncartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncartMouseClicked
System.out.println("Button clicked");  
        int selectedRow = tblw.getSelectedRow();
        if (selectedRow != -1) { // A row is selected  
            String id = tblw.getValueAt(selectedRow, 0).toString();
            String itemName = tblw.getValueAt(selectedRow, 1).toString();
            double price = Double.parseDouble(tblw.getValueAt(selectedRow, 10).toString());
            String quantityInput = JOptionPane.showInputDialog(this, "Enter quantity for " + itemName + ":");
        try {
            int quantity = Integer.parseInt(quantityInput);
            if (quantity < 1) {
                JOptionPane.showMessageDialog(this, "Invalid quantity. Please enter a positive number.");
            } else {
                double total = price * quantity;
              System.out.println(id+" " +itemName+" "+ price+" "+total);
               cart.addToCart(id, itemName, price, quantity, total); 
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid input. Please enter a valid quantity.");
        }
              
}                // TODO add your handling code here:
    }//GEN-LAST:event_btncartMouseClicked

    private void btnbillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbillMouseClicked
 Cart cart=new Cart();
        cart.setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_btnbillMouseClicked

    private void lblptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblptMouseClicked
PowerToolss pt=new PowerToolss();  
pt.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_lblptMouseClicked

    private void lblhtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhtMouseClicked
Handtools ht=new Handtools(); 
ht.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_lblhtMouseClicked

    private void lblaccessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblaccessMouseClicked
Accessories ac=new Accessories();
ac.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_lblaccessMouseClicked

    private void lblspMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblspMouseClicked
SpareParts sp=new SpareParts();
sp.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_lblspMouseClicked

    private void lblwireMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblwireMouseClicked
Wire w=new Wire();
w.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_lblwireMouseClicked

    private void btnwarningMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnwarningMouseClicked
Warning wra=new Warning();
wra.generateWarningReport();        // TODO add your handling code here:
    }//GEN-LAST:event_btnwarningMouseClicked

    private void btncustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncustomerMouseClicked
Cus c=new Cus();
c.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btncustomerMouseClicked

    private void btnchiselMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnchiselMouseClicked
ChiselDetails ch=new ChiselDetails();
ch.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnchiselMouseClicked

    private void btnbitsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbitsMouseClicked
Bits bit=new Bits();
bit.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnbitsMouseClicked

    private void btnsafegaurdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsafegaurdMouseClicked
SafeGaurd sg=new SafeGaurd();
sg.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnsafegaurdMouseClicked

    private void btnhandleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhandleMouseClicked
Handle han=new Handle();
han.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnhandleMouseClicked

    private void btnchucknutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnchucknutMouseClicked
ChuckNut cn=new ChuckNut();
cn.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnchucknutMouseClicked

    private void btnkeysMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkeysMouseClicked
Keys k=new Keys();
k.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnkeysMouseClicked

    private void btnweldingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnweldingMouseClicked
Welding wed=new Welding();
wed.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnweldingMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WeldingFields.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WeldingFields.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WeldingFields.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WeldingFields.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WeldingFields().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Id;
    private javax.swing.JLabel brand;
    private javax.swing.JLabel btnadd;
    private javax.swing.JLabel btnbill;
    private javax.swing.JLabel btnbits;
    private javax.swing.JLabel btncart;
    private javax.swing.JLabel btnchisel;
    private javax.swing.JLabel btnchucknut;
    private javax.swing.JLabel btncustomer;
    private javax.swing.JLabel btnhandle;
    private javax.swing.JLabel btnkeys;
    private javax.swing.JLabel btnsafegaurd;
    private javax.swing.JLabel btnupdate;
    private javax.swing.JLabel btnwarning;
    private javax.swing.JLabel btnwelding;
    private javax.swing.JComboBox<String> combobrand;
    private javax.swing.JLabel cp;
    private javax.swing.JLabel godam;
    private javax.swing.JLabel in;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblaccess;
    private javax.swing.JLabel lblht;
    private javax.swing.JLabel lblpt;
    private javax.swing.JLabel lblsp;
    private javax.swing.JLabel lblwire;
    private javax.swing.JLabel mn;
    private javax.swing.JLabel res;
    private javax.swing.JLabel sr;
    private javax.swing.JTable tblw;
    private javax.swing.JTextField txtcp;
    private javax.swing.JTextField txtgodam;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtin;
    private javax.swing.JTextField txtmn;
    private javax.swing.JTextField txtrs;
    private javax.swing.JTextField txtsearch;
    private javax.swing.JTextField txtsr;
    private javax.swing.JTextField txtws;
    private javax.swing.JLabel ws;
    // End of variables declaration//GEN-END:variables
}
